import Link from "next/link";

export default function Home() {
  return <main className="marketing">
    <nav className="marketing-nav"><Link href="/" className="brand"><span className="brand-mark">F</span><span>FlowDesk</span></Link><div><a href="#product">Продукт</a><a href="#workflow">Як працює</a><a href="#security">Безпека</a><Link href="/case-study">Case study</Link></div><span><Link className="nav-login" href="/login">Увійти</Link><Link className="primary" href="/onboarding">Спробувати демо</Link></span></nav>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">CRM для команд, які ростуть</span><h1>Ведіть клієнтів.<br/>Рухайте угоди.<br/><em>Не втрачайте темп.</em></h1><p>FlowDesk об’єднує продажі, завдання й командну роботу в одному спокійному робочому просторі — без складного впровадження.</p><div className="hero-actions"><Link className="primary large" href="/onboarding">Створити робочий простір →</Link><Link className="secondary large" href="/app">Відкрити демо</Link></div><small>Без картки · Демонстраційні дані · 2 хвилини до старту</small></div><div className="hero-product"><div className="product-window"><div className="fake-sidebar"><span className="brand-mark">F</span>{[1,2,3,4,5].map((x)=><i key={x}/>)}</div><div className="fake-main"><header><span>Огляд</span><b/><b/></header><div className="fake-welcome"><small>ДОБРИЙ ДЕНЬ, ОЛЕКСАНДРЕ</small><strong>Команда тримає темп.</strong></div><div className="fake-metrics"><i/><i/><i/></div><div className="fake-grid"><section><strong>Фокус на сьогодні</strong>{[1,2,3].map((x)=><p key={x}><b/><span/></p>)}</section><section><strong>Воронка продажів</strong>{[90,72,54,36].map((x)=><p key={x}><i style={{width:`${x}%`}}/></p>)}</section></div></div></div><div className="floating-card top"><span>↗</span><div><strong>+18%</strong><small>темп тижня</small></div></div><div className="floating-card bottom"><span>✓</span><div><strong>Угоду переміщено</strong><small>Пропозиція → Переговори</small></div></div></div></section>
    <section className="trust"><span>Створено для невеликих команд</span><div><b>NORTHLINE</b><b>FORMA</b><b>SOLIS</b><b>GREENWAY</b><b>ATELIER №7</b></div></section>
    <section id="product" className="marketing-section"><div className="section-heading"><span className="eyebrow">Один робочий ритм</span><h2>Усе важливе — перед очима.</h2><p>Від першого звернення до завершеної роботи. Кожна дія пов’язана, відповідальна людина зрозуміла, а наступний крок не губиться.</p></div><div className="feature-grid"><article className="feature large-feature"><span>01 · PIPELINE</span><h3>Продажі, які видно.</h3><p>Перетягуйте угоди між етапами, фіксуйте бюджет і наступну дію. Прогноз оновиться автоматично.</p><div className="mini-kanban">{["Новий лід","Пропозиція","Переговори"].map((x,i)=><div key={x}><b>{x}</b><article style={{transform:`translateY(${i*5}px)`}}><small>{["Horizon Development","Solis Coffee","Atelier No. 7"][i]}</small><strong>{["185 000 ₴","146 000 ₴","315 000 ₴"][i]}</strong></article></div>)}</div></article><article className="feature"><span>02 · CLIENTS</span><h3>Повна картина клієнта.</h3><p>Контакти, угоди, завдання й історія — в одному профілі.</p><div className="client-stack"><i>SO</i><i>FO</i><i>UR</i><b>+12</b></div></article><article className="feature dark-feature"><span>03 · FOCUS</span><h3>Наступна дія завжди поруч.</h3><p>Пріоритети, дедлайни та відповідальні — без ранкових статус-колів.</p><div className="focus-demo"><b>03</b><span>Завдання на сьогодні</span><i>2 у роботі</i></div></article></div></section>
    <section id="workflow" className="workflow-section"><div className="section-heading"><span className="eyebrow">Від ліда до результату</span><h2>Процес, який команда розуміє.</h2></div><div className="workflow-steps">{[["01","Додайте клієнта","Збережіть компанію та контактну особу."],["02","Створіть угоду","Зафіксуйте бюджет, джерело і наступний крок."],["03","Рухайте pipeline","Змінюйте етапи — історія й прогноз оновляться."],["04","Доведіть до результату","Призначте завдання та бачте спільний прогрес."]].map(([n,t,p])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></article>)}</div></section>
    <section id="security" className="security-section"><div><span className="eyebrow">Безпека за замовчуванням</span><h2>Дані кожної команди ізольовані.</h2><p>FlowDesk проєктувався як multi-tenant продукт: дані прив’язані до робочого простору, доступ перевіряється на сервері, а ролі визначають дозволені дії.</p><Link href="/case-study">Переглянути архітектуру →</Link></div><div className="security-card"><span className="shield">◇</span><div><small>WORKSPACE ISOLATION</small><strong>Northline Studio</strong><p>Owner · Admin · Member</p></div><i>Захищено</i></div></section>
    <section className="cta"><span className="eyebrow">Готові навести лад?</span><h2>Зберіть клієнтів, угоди<br/>й завдання в одному місці.</h2><Link href="/onboarding" className="primary large">Почати з FlowDesk →</Link><p>FlowDesk — вигаданий SaaS-концепт, створений для портфоліо. Усі дані демонстраційні.</p></section>
    <footer><Link href="/" className="brand"><span className="brand-mark">F</span><span>FlowDesk</span></Link><p>Спокійний контроль для амбітних команд.</p><div><Link href="/case-study">Case study</Link><a href="#security">Безпека</a><a href="mailto:hello@flowdesk.demo">Контакти</a></div><span>© 2026 FlowDesk</span></footer>
  </main>;
}
